#!/usr/bin/env ruby
# encoding: utf-8

$COLOR_RESET         = "\e[0m"

$COLOR_BLACK         = "\e[30m"
$COLOR_RED           = "\e[31m"
$COLOR_GREEN         = "\e[32m"
$COLOR_YELLOW        = "\e[33m"
$COLOR_BLUE          = "\e[34m"
$COLOR_MAGENTA       = "\e[35m"
$COLOR_CYAN          = "\e[36m"
$COLOR_WHITE         = "\e[37m"

$COLOR_BLACK_I       = "\e[90m"
$COLOR_RED_I         = "\e[91m"
$COLOR_GREEN_I       = "\e[92m"
$COLOR_YELLOW_I      = "\e[93m"
$COLOR_BLUE_I        = "\e[94m"
$COLOR_MAGENTA_I     = "\e[95m"
$COLOR_CYAN_I        = "\e[96m"
$COLOR_WHITE_I       = "\e[97m"

$COLOR_BLACK_B       = "\e[1;30m"
$COLOR_RED_B         = "\e[1;31m"
$COLOR_GREEN_B       = "\e[1;32m"
$COLOR_YELLOW_B      = "\e[1;33m"
$COLOR_BLUE_B        = "\e[1;34m"
$COLOR_MAGENTA_B     = "\e[1;35m"
$COLOR_CYAN_B        = "\e[1;36m"
$COLOR_WHITE_B       = "\e[1;37m"

$COLOR_BLACK_U       = "\e[4;30m"
$COLOR_RED_U         = "\e[4;31m"
$COLOR_GREEN_U       = "\e[4;32m"
$COLOR_YELLOW_U      = "\e[4;33m"
$COLOR_BLUE_U        = "\e[4;34m"
$COLOR_MAGENTA_U     = "\e[4;35m"
$COLOR_CYAN_U        = "\e[4;36m"
$COLOR_WHITE_U       = "\e[4;37m"

$COLOR_BLACK_L       = "\e[5;30m"
$COLOR_RED_L         = "\e[5;31m"
$COLOR_GREEN_L       = "\e[5;32m"
$COLOR_YELLOW_L      = "\e[5;33m"
$COLOR_BLUE_L        = "\e[5;34m"
$COLOR_MAGENTA_L     = "\e[5;35m"
$COLOR_CYAN_L        = "\e[5;36m"
$COLOR_WHITE_L       = "\e[5;37m"

$COLOR_BG_BLACK      = "\e[40m"
$COLOR_BG_RED        = "\e[41m"
$COLOR_BG_GREEN      = "\e[42m"
$COLOR_BG_YELLOW     = "\e[43m"
$COLOR_BG_BLUE       = "\e[44m"
$COLOR_BG_MAGENTA    = "\e[45m"
$COLOR_BG_CYAN       = "\e[46m"
$COLOR_BG_WHITE      = "\e[47m"